### ISSUE TITLE
App crash with verve android sdk

### ISSUE THREAD

**Issue by andybui2014** [VerveWireless/verve-ios-adsdk#6]
When we user my app, sometime app crash

java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:799)
	at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1248)
	at com.vervewireless.advert.location.a.l(Unknown Source)
	at com.vervewireless.advert.location.a.a(Unknown Source)
	at com.vervewireless.advert.location.LocationHandler.<init>(Unknown Source)
	at com.vervewireless.advert.location.a.<init>(Unknown Source)
	at com.vervewireless.advert.location.LocationProxy.a(Unknown Source)
	at com.vervewireless.advert.location.LocationProxy.init(Unknown Source)
	at com.vervewireless.advert.adattribution.VerveSupportService.a(Unknown Source)
	at com.vervewireless.advert.adattribution.VerveSupportService.a(Unknown Source)
	at com.vervewireless.advert.adattribution.VerveSupportService$1.onLatInfoReceived(Unknown Source)
	at com.vervewireless.advert.adattribution.LatChecker$a.a(Unknown Source)
	at com.vervewireless.advert.adattribution.LatChecker$a.onPostExecute(Unknown Source)

**Comment by sbverve** [comment]
Hi @andybui2014 , we'd like to get more information from you to address this crash.  Please email integration@vervemobile.com at your earliest convenience.
